<?php
\Drupal::service('class_loader')->add('Djambi', array(__DIR__ . '/src'));

/**
 * Implements hook_theme().
 */
function djambi_theme() {
  return array(
    'djambi_grid' => array(
      'render element' => 'form',
      'file' => 'djambi.theme.inc',
    ),
    'djambi_cardinal_grid' => array(
      'variables' => array(
        'cells' => NULL,
        'caption' => NULL,
        'attributes' => array(),
      ),
      'function' => 'theme_djambi_cardinal_grid',
      'file' => 'djambi.theme.inc',
    ),
    // TODO créer fonction de thème pour la grille hexagonale
    'djambi_hexagonal_grid' => array(
      'variables' => array(
        'cells' => NULL,
        'caption' => NULL,
        'attributes' => array(),
      ),
    ),
    'djambi_cell' => array(
      'variables' => array('cell' => NULL, 'game' => NULL),
      'file' => 'djambi.theme.inc',
    ),
    'djambi_piece' => array(
      'variables' => array('piece' => NULL),
      'file' => 'djambi.theme.inc',
    ),
    'djambi_piece_full_name' => array(
      'variables' => array(
        'piece' => NULL,
        'html' => TRUE,
        'display_dead_name' => FALSE,
      ),
      'file' => 'djambi.theme.inc',
    ),
    'djambi_faction_full_name' => array(
      'variables' => array('faction' => NULL, 'html' => TRUE),
    ),
    'djambi_piece_log' => array(
      'variables' => array(
        'piece' => NULL,
        'dead' => NULL,
      ),
      'file' => 'djambi.theme.inc',
    ),
    'djambi_last_move_item' => array(
      'variables' => array(
        'time' => NULL,
        'side' => NULL,
        'description' => NULL,
      ),
    ),
    'description_list' => array(
      'variables' => array('groups' => array(), 'attributes' => array()),
      'file' => 'djambi.html.inc',
    ),
  );
}

/**
 *  Implements hook_help().
 */
function djambi_help($route_name) {
  switch($route_name) {
    case('djambi.sandbox'):
      return '<p>' . t("Welcome to Djambi dojo room. You can play here a Djambi game where you control successively all sides to learn Djambi basic rules, to experiment new tactics or to play with (future ex-)friends in a hot chair mode.") . '</p>';
  }
}


/**
 *  Implements hook_cron().
 */
function djambi_cron() {
  if (\Drupal::service('djambi.tempstore') instanceof \Drupal\djambi\Services\DjambiTempStoreFactory) {
    \Drupal::service('djambi.tempstore')->garbageCollection();
  }
}