<?php
/**
 * Implements hook_permission().
 */
function djambi_permission() {
  return array(
    'play djambi sandbox game' => array(
      'title' => t('Play Djambi sandbox game'),
      'description' => t('Initiate and play a single player Djambi sandbox game.'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function djambi_theme() {
  return array(
    'djambi_grid' => array(
      'render element' => 'form',
      'file' => 'djambi.theme.inc',
      'template' => 'djambi-grid',
    ),
    'djambi_cardinal_grid' => array(
      'variables' => array('game' => NULL, 'cells' => NULL, 'caption' => NULL),
      'file' => 'djambi.theme.inc',
    ),
    'djambi_hexagonal_grid' => array(
      'variables' => array('game' => NULL, 'cells' => NULL, 'caption' => NULL),
      'template' => 'djambi-hexagonal-grid',
    ),
    'djambi_cell' => array(
      'variables' => array('cell' => NULL),
      'template' => 'djambi-cell',
      'file' => 'djambi.theme.inc',
    ),
    'djambi_piece' => array(
      'variables' => array('piece' => NULL),
      'template' => 'djambi-piece',
      'file' => 'djambi.theme.inc',
    ),
    'djambi_piece_full_name' => array(
      'variables' => array(
        'piece' => NULL,
        'html' => TRUE,
        'display_dead_name' => FALSE,
      ),
      'template' => 'djambi-piece-full-name',
    ),
    'djambi_faction_full_name' => array(
      'variables' => array('faction' => NULL, 'html' => TRUE),
      'template' => 'djambi-faction-full-name',
    ),
  );
}
