<?php
function kw_djambi_captcha_form_user_register_form_alter(&$form, &$form_state) {
  form_load_include($form_state, 'inc', 'kw_djambi', 'kw_djambi.form');
  if (!empty($form_state['kw_djambi']['selected_piece']) && !$form_state['kw_djambi']['change_turn']) {
    $piece = $form_state['kw_djambi']['selected_piece'];
    $grid = $piece->getFaction()->getBattlefield();
  }
  elseif (isset($form_state['saved_grid'])) {
    if (isset($form_state['kw_djambi']['change_turn'])) {
      unset($form_state['kw_djambi']);
    }
    $grid = new DjambiBattlefield($form_state['saved_grid']);
    $grid->play();
  }
  else {
    $grid = new DjambiBattlefield(array(
      'mode' => KW_DJAMBI_MODE_TRAINING,
      'disposition' => '2mini',
      'savable' => FALSE,
      'computers' => array(
        2 => 'DjambiIADummy'
      ),
      'is_new' => TRUE,
    ));
    $grid->setOption('turns_before_draw_proposal', -1);
    $grid->setInfo('interface', 'minimal');
    $grid->play();
  }
  _kw_djambi_build_game_form($form, $form_state, $grid, array(
    'show_rules' => FALSE,
    'show_stats' => FALSE,
    'show_log' => FALSE,
  ));
  if (!$grid->isFinished()) {
    $game_status_msg = '<div class="messages warning">' . t("You have to beat a dummy computer opponent in a mini djambi game to complete your registration !") . ' </div>';
  }
  elseif ($form_state['kw_djambi']['result'] == KW_DJAMBI_USER_WINNER) {
    $game_status_msg = '<div class="messages status">' . t("Congratulations, you are smarter than a dummy computer. You can now complete your registration.") . ' </div>';
  }
  else {
    $game_status_msg = '<div class="messages error">' . t("Shame on you, you failed beating a dummy computer.") . ' </div>';
    $form['grid']['retry'] = array(
        '#type' => 'submit',
        '#limit_validation_errors' => array(),
        '#submit' => array('kw_djambi_captcha_retry_submit'),
        '#value' => t('Try again...'),
        '#weight' => -19
    );
  }
  $form['grid']['captcha'] = array(
      '#weight' => -20,
      '#markup' => $game_status_msg
  );
  $form['grid']['#weight'] = 1;
  $form['#validate'][] = 'kw_djambi_captcha_registration_validate';
}

function kw_djambi_captcha_registration_validate($form, &$form_state) {
  if (!isset($form_state['kw_djambi']['result'])) {
    form_set_error('grid', t("Computer is still alive !"));
  }
  elseif ($form_state['kw_djambi']['result'] != KW_DJAMBI_USER_WINNER) {
    form_set_error('grid', t("You are not smart enough to register."));
  }
}

function kw_djambi_captcha_retry_submit($form, &$form_state) {
  $form_state['rebuild'] = TRUE;
  unset($form_state['saved_grid']);
  unset($form_state['kw_djambi']);
}