<?php
/**
 * @file
 * Gère l'affichage et le formulaire de messages instantanés liés à une partie
 * de Djambi.
 */

/**
 * Implements hook_theme().
 */
function djambi_chat_theme() {
  return array(
    'djambi_chat' => array(
      'variables' => array(
        'messages' => array(),
        'form' => NULL,
        'attributes' => array(),
      ),
    ),
  );
}

/**
 * Implements hook_node_view().
 */
function djambi_chat_node_view($node, $view_mode) {
  if ($node->type == 'djambi' && $view_mode == 'full') {
    /* @var $grid DjambiBattlefield */
    $grid = $node->content['grid']['#grid'];
    $messages = _djambi_chat_display_messages($grid);
    if ($grid->isPending() || $grid->isNotBegin()) {
      $form = drupal_get_form('djambi_chat_add_message_form', $grid);
    }
    else {
      $form = NULL;
    }
    $node->content['chat'] = array(
      '#markup' => theme('djambi_chat', array(
        'messages' => $messages,
        'form' => $form,
      )),
    );
  }
}

/**
 * Affichage des messages d'un chat.
 */
function _djambi_chat_display_messages(DjambiBattlefield $grid) {
  $messages = array();
  return $messages;
}

/**
 * Formulaire d'ajout de messages sur le chat.
 */
function djambi_chat_add_message_form($form, &$form_state, DjambiBattlefield $grid) {
  $form['new_message'] = array(
    '#type' => 'textfield',
    '#title' => t('New message'),
  );
  $form['send'] = array(
    '#type' => 'submit',
    '#value' => t('Send'),
  );
  return $form;
}

/**
 * Traitement du formulaire d'ajout de messages.
 */
function djambi_chat_add_message_form_submit($form, &$form_state) {

}

/**
 * Affichage du chat.
 */
function theme_djambi_chat($variables) {
  $form = $variables['form'];
  $messages = $variables['messages'];
  $attributes = $variables['attributes'];
  $attributes['class'][] = 'djambi-chat';
  $html = '<div' . drupal_attributes($attributes) . '>';
  $html .= drupal_render($form);
  $html .= '</div>';
  return $html;
}